language: bash
sudo: true

env:
  - INSTALL_SCRIPT="bin/install.sh" ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR/.."

before_script:
    - pwd
    - $INSTALL_SCRIPT 
    - ls -altr
    - ls -altr bin
    - ls -altr bin/gs_350

script:
- echo $TRAVIS_BUILD_DIR
- echo $ROWAN_PROJECTS_HOME
- bash bin/travisTest.sh  

notifications:
  slack: gemtalksystems:4YWbzy6sJN9cE0FhxvUPP8nS

